main: me.mrletsplay.playerradios.Main
name: PlayerRadios
version: "3.0b3"
author: MrLetsplay2003
api-version: 1.13
softdepend: [PlaceholderAPI, MrCore_BukkitImpl]

commands:
  playerradios:
    aliases: [pr]
